# Generated by Django 4.1 on 2023-01-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0006_proposal_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='sender',
            new_name='senderEmail',
        ),
    ]
