# Generated by Django 4.1 on 2023-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0007_rename_sender_proposal_senderemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='transform',
            field=models.CharField(blank=True, default='', max_length=199, null=True),
        ),
    ]
