# Generated by Django 4.1 on 2023-01-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0008_element_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='size',
            field=models.CharField(blank=True, default='', max_length=199, null=True),
        ),
    ]
