# Generated by Django 4.1 on 2023-01-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0009_element_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bgImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
