# Generated by Django 4.1 on 2023-01-22 22:42

import Proposal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0010_page_bgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=Proposal.models.upload_element),
        ),
        migrations.AlterField(
            model_name='page',
            name='bgImage',
            field=models.FileField(blank=True, null=True, upload_to=Proposal.models.upload_page),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=Proposal.models.upload_proposal),
        ),
    ]
