# Generated by Django 4.1 on 2022-10-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, default='profile', max_length=199, null=True),
        ),
    ]
