# Generated by Django 4.1 on 2022-10-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_rename_organization_clientorganization_company'),
        ('Console', '0003_rename_client_org_project_clientorg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clientOrg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Organization.clientorganization'),
        ),
    ]
