# Generated by Django 4.1 on 2022-10-06 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organization', '0004_rename_organization_clientorganization_company'),
        ('Console', '0004_alter_project_clientorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accountManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverableManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_deliverable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_estimator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='fieldManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_field', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='first_name',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hibernate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_name',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subCategory',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='surveyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_surveyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='clientOrg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='Organization.clientorganization'),
        ),
    ]
