# Generated by Django 4.1 on 2022-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0006_alter_project_enddate_alter_project_hibernate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hibernate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
