# Generated by Django 4.1 on 2022-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0007_alter_project_enddate_alter_project_hibernate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hibernate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='startDate',
        ),
    ]
