# Generated by Django 4.1 on 2022-10-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0009_alter_project_accountmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nickname',
            field=models.CharField(blank=True, default='profile', max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.CharField(blank=True, max_length=299, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_name',
            field=models.CharField(blank=True, max_length=299, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_name',
            field=models.CharField(blank=True, max_length=299, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=499, null=True),
        ),
    ]
