# Generated by Django 4.1 on 2022-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0010_project_nickname_alter_project_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=199, null=True),
        ),
    ]
