# Generated by Django 4.1 on 2022-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_profile_isfreeuser'),
        ('Console', '0012_rename_first_name_project_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ManyToManyField(related_name='project', to='User.profile'),
        ),
    ]
