# Generated by Django 4.1 on 2022-10-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0005_alter_organization_number'),
        ('Console', '0013_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clientOrg',
        ),
        migrations.AddField(
            model_name='project',
            name='clientOrg',
            field=models.ManyToManyField(related_name='project', to='Organization.clientorganization'),
        ),
    ]
