# Generated by Django 4.1 on 2022-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0014_remove_project_clientorg_project_clientorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=5999, null=True),
        ),
    ]
