# Generated by Django 4.1 on 2022-10-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0016_alter_project_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stageHistory',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
    ]
