# Generated by Django 4.1 on 2022-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0018_alter_project_stagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stageStatus',
            field=models.CharField(blank=True, default='next', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stageHistory',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
    ]
