# Generated by Django 4.1 on 2023-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0013_remove_element_pageid'),
        ('Console', '0022_remove_project_deliverablemanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proposals',
            field=models.ManyToManyField(related_name='project', to='Organization.proposal'),
        ),
    ]
