# Generated by Django 4.1 on 2023-01-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0023_project_proposals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='proposals',
        ),
    ]
