# Generated by Django 4.1 on 2023-03-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_profile_isprevilagechange'),
        ('Console', '0025_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client',
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='User.profile'),
        ),
    ]
