# Generated by Django 4.1 on 2023-03-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_profile_isprevilagechange'),
        ('Console', '0026_remove_ticket_client_ticket_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='User.profile'),
        ),
    ]
