# Generated by Django 4.1 on 2023-03-06 04:08

import Console.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0015_remove_page_proposal_remove_page_section_and_more'),
        ('Console', '0028_ticket_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to=Console.models.upload_audio),
        ),
        migrations.AddField(
            model_name='ticket',
            name='audioInfo',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='Organization.organization'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, max_length=499, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=499, null=True),
        ),
        migrations.CreateModel(
            name='TicketPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Console.models.upload_icon_picture)),
                ('ticket', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketPicture', to='Console.ticket')),
            ],
        ),
    ]
