# Generated by Django 4.1 on 2023-03-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0015_remove_page_proposal_remove_page_section_and_more'),
        ('Console', '0029_ticket_audiofile_ticket_audioinfo_ticket_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='Organization.organization'),
        ),
    ]
