# Generated by Django 4.1 on 2023-03-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0015_remove_page_proposal_remove_page_section_and_more'),
        ('Console', '0030_alter_ticket_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='clientOrg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='Organization.clientorganization'),
        ),
    ]
