# Generated by Django 4.1 on 2023-03-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0031_ticket_clientorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='icons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
