# Generated by Django 4.1 on 2023-03-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0032_ticket_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='detail',
        ),
    ]
