# Generated by Django 4.1 on 2023-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0035_alter_ticket_clientchat_alter_ticket_internalchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='surveyID',
            field=models.CharField(blank=True, max_length=499, null=True),
        ),
    ]
