# Generated by Django 4.1 on 2023-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0036_ticket_surveyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='icons',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
