# Generated by Django 4.1 on 2023-03-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0037_alter_ticket_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seenByAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seenByClient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='surveyID',
            field=models.CharField(blank=True, default='', max_length=499, null=True),
        ),
    ]
