# Generated by Django 4.1 on 2023-03-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0041_chatfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatfile',
            old_name='picture',
            new_name='file',
        ),
    ]
