# Generated by Django 4.1 on 2022-10-03 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_clientorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorganization',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_org', to='Organization.organization'),
        ),
    ]
