# Generated by Django 4.1 on 2022-10-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_clientorganization_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientorganization',
            old_name='organization',
            new_name='company',
        ),
    ]
