# Generated by Django 4.1 on 2022-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_rename_organization_clientorganization_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='number',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
