# Generated by Django 4.1 on 2023-01-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_alter_clientorganization_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=199, null=True)),
                ('company', models.ManyToManyField(to='Organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionid', models.IntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=199, null=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='Organization.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageid', models.IntegerField(blank=True, default=1, null=True)),
                ('color', models.CharField(blank=True, max_length=199, null=True)),
                ('bgUrl', models.CharField(blank=True, max_length=599, null=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='Organization.proposal')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='Organization.section')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementid', models.IntegerField(blank=True, default=1, null=True)),
                ('typpe', models.CharField(blank=True, max_length=199, null=True)),
                ('loc', models.CharField(blank=True, max_length=199, null=True)),
                ('configuration', models.CharField(blank=True, max_length=199, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('imgSize', models.CharField(blank=True, max_length=199, null=True)),
                ('imgUrl', models.CharField(blank=True, max_length=799, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='Organization.page')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='Organization.proposal')),
            ],
        ),
    ]
