# Generated by Django 4.1 on 2023-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0008_proposal_proposalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='no',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
