# Generated by Django 4.1 on 2023-01-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0009_page_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='typpe',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
