# Generated by Django 4.1 on 2023-01-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0010_proposal_typpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='Organization.section'),
        ),
    ]
