# Generated by Django 4.1 on 2023-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0011_element_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='pageid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
