# Generated by Django 4.1 on 2023-01-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0012_element_pageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='pageid',
        ),
    ]
