# Generated by Django 4.1 on 2023-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0013_remove_element_pageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='configuration',
            field=models.CharField(blank=True, default='', max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='imgSize',
            field=models.CharField(blank=True, default='', max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='imgUrl',
            field=models.CharField(blank=True, default='', max_length=799, null=True),
        ),
    ]
