# Generated by Django 4.1 on 2023-01-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0014_element_text_alter_element_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='page',
            name='section',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='company',
        ),
        migrations.RemoveField(
            model_name='section',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
