# Generated by Django 4.1 on 2022-09-26 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        ('User', '0002_remove_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Organization.organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
