# Generated by Django 4.1 on 2022-10-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_clientorganization'),
        ('User', '0004_profile_address_profile_work_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clientOrg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Organization.clientorganization'),
        ),
    ]
