# Generated by Django 4.1 on 2022-10-19 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_freeuser_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freeuser',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
