# Generated by Django 4.1 on 2022-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_freeuser_date_alter_freeuser_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isFreeUser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
