# Generated by Django 4.1 on 2022-11-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_alter_clientorganization_number'),
        ('User', '0009_profile_isfreeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ManyToManyField(to='Organization.organization'),
        ),
    ]
