# Generated by Django 4.1 on 2022-11-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_profile_company_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isPrevilageChange',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
