# Generated by Django 4.1 on 2022-10-13 14:19

import Survey.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0004_survey_iconsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=Survey.models.upload_category)),
            ],
        ),
        migrations.CreateModel(
            name='IconBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('field', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Survey.category')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('iconBase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Survey.iconbase')),
                ('survey', models.ManyToManyField(to='Survey.survey')),
            ],
        ),
    ]
