# Generated by Django 4.1 on 2022-10-15 16:37

import Survey.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0007_iconbase_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='angle',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='color',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='icon',
            name='iconid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icon',
            name='opacity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='rotate',
            field=models.IntegerField(blank=True, default=45, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='xposition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='icon',
            name='yposition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='icon',
            name='survey',
        ),
        migrations.CreateModel(
            name='IconPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Survey.models.upload_icon_picture)),
                ('icon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iconPicture', to='Survey.icon')),
            ],
        ),
        migrations.AddField(
            model_name='icon',
            name='survey',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='Survey.survey'),
        ),
    ]
