# Generated by Django 4.1 on 2022-10-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0009_icon_audiofile_icon_audioinfo_icon_dateupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cctvpicture',
            name='cctv',
        ),
        migrations.DeleteModel(
            name='CCTV',
        ),
        migrations.DeleteModel(
            name='CCTVPicture',
        ),
    ]
