# Generated by Django 4.1 on 2022-10-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0012_rename_first_name_project_firstname_and_more'),
        ('Survey', '0010_remove_cctvpicture_cctv_delete_cctv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconbase',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='Console.project'),
        ),
    ]
