# Generated by Django 4.1 on 2022-10-18 12:18

import Survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0011_alter_iconbase_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=Survey.models.upload_icon),
        ),
    ]
