# Generated by Django 4.1 on 2022-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0012_icon_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
