# Generated by Django 4.1 on 2022-10-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0013_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
