# Generated by Django 4.1 on 2022-10-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0015_alter_iconbase_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='stage',
            field=models.CharField(blank=True, default='profile', max_length=100, null=True),
        ),
    ]
