# Generated by Django 4.1 on 2022-10-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0016_survey_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='dateUpdated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
