# Generated by Django 4.1 on 2022-10-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0017_alter_icon_dateupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='stageStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
