# Generated by Django 4.1 on 2022-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0018_survey_stagestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='stageStatus',
            field=models.CharField(blank=True, default='next', max_length=100, null=True),
        ),
    ]
