# Generated by Django 4.1 on 2022-11-02 15:18

import Survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0019_alter_survey_stagestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Survey.models.upload_file_survey),
        ),
    ]
