# Generated by Django 4.1 on 2022-11-02 17:56

import Survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0021_alter_survey_file_alter_survey_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Survey.models.upload_file_survey),
        ),
        migrations.AlterField(
            model_name='survey',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=Survey.models.upload_picture_location),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyPicture',
            field=models.ImageField(blank=True, null=True, upload_to=Survey.models.upload_picture_location),
        ),
    ]
