# Generated by Django 4.1 on 2022-11-09 21:22

import Survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0022_alter_survey_file_alter_survey_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=Survey.models.upload_file_pdf),
        ),
    ]
