# Generated by Django 4.1 on 2022-11-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0025_icon_comment_icon_enddate_icon_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='iconSize',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
    ]
