# Generated by Django 4.1 on 2022-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0027_icon_isreported'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='senderReportEmail',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
