# Generated by Django 4.1 on 2022-12-06 20:16

import Survey.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0028_icon_senderreportemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('iconid', models.IntegerField(blank=True, default=1, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('color', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('xposition', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yposition', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('isLocked', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=Survey.models.upload_icon)),
                ('isReported', models.BooleanField(default=False)),
                ('senderReportEmail', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('line', models.TextField(blank=True, default='', null=True)),
                ('audioInfo', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('audioFile', models.FileField(blank=True, null=True, upload_to=Survey.models.upload_audio)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('endDate', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('techName', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('test', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('iconBase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable', to='Survey.iconbase')),
                ('survey', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cable', to='Survey.survey')),
            ],
        ),
    ]
