# Generated by Django 4.1 on 2022-12-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0030_remove_cable_xposition_remove_cable_yposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='label',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
