# Generated by Django 4.1 on 2022-12-08 19:46

import Survey.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0031_cable_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='iconBase',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('sectionid', models.IntegerField(blank=True, default=1, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('color', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('isReported', models.BooleanField(default=False)),
                ('senderReportEmail', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('audioInfo', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('audioFile', models.FileField(blank=True, null=True, upload_to=Survey.models.upload_audio)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('cable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='Survey.cable')),
            ],
        ),
    ]
