# Generated by Django 4.1 on 2022-12-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0032_remove_cable_iconbase_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='audioFile',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='audioInfo',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='dateUpdated',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='isReported',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='senderReportEmail',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='techName',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='test',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='iconpicture',
            name='cable',
        ),
        migrations.AddField(
            model_name='iconpicture',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionPicture', to='Survey.section'),
        ),
    ]
