# Generated by Django 4.1 on 2022-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0034_section_x1_section_x2_section_y1_section_y2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
