# Generated by Django 4.1 on 2022-12-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0035_cable_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='iconParent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cable', to='Survey.icon'),
        ),
    ]
