# Generated by Django 4.1 on 2022-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0036_cable_iconparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='endDate',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='startDate',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='techName',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='test',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
