# Generated by Django 4.1 on 2022-12-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0040_section_label_section_note_section_pathtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='label',
        ),
        migrations.AddField(
            model_name='icon',
            name='iconRotate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
