# Generated by Django 4.1 on 2022-12-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0041_remove_section_label_icon_iconrotate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='depth',
        ),
    ]
