# Generated by Django 4.1 on 2022-12-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0042_remove_cable_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
