# Generated by Django 4.1 on 2023-01-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0024_remove_project_proposals'),
        ('Survey', '0043_cable_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconbase',
            name='project',
            field=models.ManyToManyField(related_name='iconBase', to='Console.project'),
        ),
    ]
