# Generated by Django 4.1 on 2023-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0046_alter_icon_iconid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='iconid',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True),
        ),
    ]
