# Generated by Django 4.1 on 2023-02-17 09:03

import Survey.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0047_alter_icon_iconid'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='installationToolbar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='surveyToolbar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IconFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=Survey.models.upload_icon_file)),
                ('icon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iconFile', to='Survey.icon')),
                ('section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionFile', to='Survey.section')),
            ],
        ),
    ]
