# Generated by Django 4.1 on 2023-02-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0048_icon_comments_icon_installationtoolbar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='bgColor',
            field=models.CharField(blank=True, default='yellow', max_length=400, null=True),
        ),
    ]
