# Generated by Django 4.1 on 2023-02-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0049_icon_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='bgColor',
            field=models.CharField(blank=True, default='#ffff00', max_length=400, null=True),
        ),
    ]
