# Generated by Django 4.1 on 2023-02-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0050_alter_icon_bgcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
