# Generated by Django 4.1 on 2023-03-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0039_remove_ticket_icons'),
        ('Survey', '0051_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='ticket',
            field=models.ManyToManyField(related_name='icon', to='Console.ticket'),
        ),
    ]
