# Generated by Django 4.1 on 2023-03-26 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0054_survey_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
