# Generated by Django 4.1 on 2023-03-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0055_alter_survey_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='uid',
        ),
    ]
