# Generated by Django 4.1 on 2023-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0057_survey_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsurvey',
            name='mainSurveyID',
            field=models.CharField(blank=True, default='', max_length=900, null=True),
        ),
    ]
