# Generated by Django 4.1 on 2023-03-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0043_chatfile_ticketid'),
        ('Survey', '0058_alter_savedsurvey_mainsurveyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsurvey',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedSurvey', to='Console.project'),
        ),
    ]
