# Generated by Django 4.1 on 2023-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0059_savedsurvey_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='version',
            field=models.CharField(default='main', max_length=300),
        ),
    ]
