# Generated by Django 4.1 on 2023-04-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0060_survey_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='iconid',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
